package pl.agh.edu.engine.advertisement;

public enum AdvertisementType {
	NEWSPAPER_ADVERTISEMENT,
	TV_ADVERTISEMENT,
	RADIO_ADVERTISEMENT,
	INTERNET_ADVERTISEMENT,
	FLYERS,
	WEB_PAGE,
	SOCIAL_MEDIA,
	BOOKING_PORTALS_PROFILE
}
