name: Git Fame

on:
  pull_request:
    branches:
      - main
permissions:
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # fetch the entire history

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install git-fame
        run: pip install git-fame

      - name: Run git fame and capture output
        uses: mathiasvr/command-output@v2.0.0
        id: run-git-fame
        with:
          run: git fame --incl=.java --loc=surv --bytype -w -M -C -R ./core/src/main
        run: echo Result ${{ steps.run-git-fame.outputs.stdout }}

      - name: Comment PR
        uses: actions/github-script@v3
        env:
          OUTPUT: ${{ steps.run-git-fame.outputs.stdout }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const output = $OUTPUT;
            const message = `Here are the contributor statistics:\n\`\`\`\n${output}\n\`\`\``;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message,
            });