name: Gradle

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Allow gradlew execution
        run: chmod +x gradlew

      - name: Build and test
        run: ./gradlew clean check

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: ${{ always() || success() || failure() }}
        with:
          name: JUnit Tests
          path: reports/junit-*.xml
          reporter: jest-junit