name: Jira Ticket Check

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - '*'

jobs:
  check_jira_ticket:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Git
        run: apt-get update && apt-get install -y git

      - name: Check commit messages, PR titles, and branch names
        run: |
          # Fetch all commit messages, PR titles, and branch names
          COMMIT_MESSAGES=$(git log --pretty=format:%s ${{ github.event.before }}..${{ github.sha }})
          PR_TITLE=$(git show -s --format=%s ${{ github.event.pull_request.head.sha }})
          BRANCH_NAME=$(echo ${{ github.ref }} | sed 's/refs\/heads\///')

          # Regular expression to match Jira ticket number format "HS-21"
          JIRA_TICKET_REGEX="HS-[0-9]+"

          # Check if the Jira ticket number is present in all commit messages, PR title, and branch name
          if [[ $COMMIT_MESSAGES =~ $JIRA_TICKET_REGEX ]] && [[ $PR_TITLE =~ $JIRA_TICKET_REGEX ]] && [[ $BRANCH_NAME =~ $JIRA_TICKET_REGEX ]]; then
            echo "All commit messages, PR title, and branch name have a Jira ticket number."
          else
            echo "Jira ticket number missing in one or more: commit messages, PR title, or branch name."
            exit 1
          fi
