name: Jira Ticket Validation

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - '*'

jobs:
  ticketValidation:
    name: Ticket Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate Jira ticket numbers
        uses: ./.github/actions