name: Code Analysis

on:
  pull_request

jobs:
  branchName:
    name: Branch Validation
    runs-on: ubuntu-latest
    steps:

      - uses: octokit/request-action@v2.x
        id: get_pr_commits
        with:
          route: GET /Hotel-Simulator/Hotel-Simulator/pulls/{pull_number}/commits
          pull_number: ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate JIRA branch name and PR/commit consistency
        uses: worksome/jira-branch-name-validator-action@v2.0.0
        with:
          branch-name: ${{ github.event.pull_request.head.ref }}
          pr-title: ${{ github.event.pull_request.title }}
          commits: ${{ steps.get_pr_commits.outputs.data }}
          prefix: HS