name: Pull Request Stats

on:
  pull_request:

jobs:
  stats:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      checks: write
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@master